### ISSUE TITLE
Background added

### ISSUE THREAD

**Issue by IzabelaM** [IzabelaM/DS_project#20]
https://github.com/IzabelaM/DS_project/Design_elements/Layouts/background.png

hidden elements to be made clickable (from top):
- rapunzel
- eyelashes/tears
- school
- alcohol 
- tablets
- teacher
- secret document
- support (friends)
- social media icons (facebook and instagram)

**Comment by IzabelaM** [comment]
Hey @angelos24 

Just if you didn't notice, the file was updated today. The only thing that I've updated was the header, removed the search icon and added an IA label "Problems".

**Comment by angelos24** [comment]
Thanks @IzabelaM , I had noticed already but thanks for update :)
